import {
  Entity,
  PrimaryGeneratedColumn,
  Column,
  Index,
  OneToMany,
  CreateDateColumn,
  UpdateDateColumn,
} from 'typeorm';
import { LessonStage } from './lesson-stage.entity';

export type LessonMode = 'quick' | 'constructor';
export type LessonStatus = 'draft' | 'generating' | 'ready' | 'error';

@Entity('lessons')
export class Lesson {
  @PrimaryGeneratedColumn('uuid')
  id!: string;

  @Index()
  @Column()
  userId!: string;

  // Nullable: B2C teachers have no school; a lesson is not tied to a school.
  @Index()
  @Column({ type: 'varchar', nullable: true })
  schoolId!: string | null;

  // ── Header (filled by the teacher) ─────────────────────────────
  @Column({ nullable: true })
  unit?: string; // Глава / Unit / Раздел

  @Column({ nullable: true })
  teacherName?: string;

  @Column({ type: 'varchar', nullable: true })
  date?: string | null; // ISO date string

  @Column({ nullable: true })
  lessonNumber?: string;

  @Column({ type: 'int', nullable: true })
  grade?: number; // 1–11

  @Column({ type: 'int', nullable: true })
  presentCount?: number;

  @Column({ type: 'int', nullable: true })
  absentCount?: number;

  @Column({ nullable: true })
  subject?: string;

  @Column({ nullable: true })
  lessonTitle?: string;

  @Column({ type: 'varchar', nullable: true })
  languageFocus?: string | null; // only for language subjects

  @Column({ type: 'jsonb', default: () => "'[]'" })
  learningObjectives!: string[]; // codes e.g. "7.6.7.1"

  // ── Lesson objectives (generated by Haiku, single list) ────────
  @Column({ type: 'jsonb', default: () => "'[]'" })
  lessonObjectives!: string[];

  // ── Value links (teacher picks month → value from reference) ───
  @Column({ type: 'varchar', nullable: true })
  valueMonth?: string | null; // "03"
  @Column({ type: 'varchar', nullable: true })
  valueLink?: string | null; // resolved value text

  @Column({ type: 'int', default: 45 })
  durationMinutes!: number;

  // ── Generated ──────────────────────────────────────────────────
  @Column({ type: 'text', nullable: true })
  homework?: string | null;

  @Column({ type: 'enum', enum: ['quick', 'constructor'], default: 'quick' })
  mode!: LessonMode;

  @Column({ type: 'enum', enum: ['draft', 'generating', 'ready', 'error'], default: 'draft' })
  status!: LessonStatus;

  @Column({ type: 'text', nullable: true })
  generationError?: string | null;

  @Column({ type: 'int', default: 0 })
  totalPoints!: number;

  @OneToMany(() => LessonStage, (stage) => stage.lesson, { cascade: true })
  stages!: LessonStage[];

  @CreateDateColumn()
  createdAt!: Date;

  @UpdateDateColumn()
  updatedAt!: Date;
}
